### ISSUE TITLE
Missing string for language name

### ISSUE THREAD

**Issue by 4sensegaming** [sooslandia/translations#18]
I just noticed there is no string for the actual language name (e.g. Czech = čeština) in the po file itself. This results in the game calling the language e.g. Czech (i.e. using the English word) on the language selection screen even when Czech is currently the active language. It's just a minor detail though.

**Comment by Danstiv** [comment]
We do not currently support this feature, the language name is the English name according to the ISO 639-1 standard.

**Comment by Danstiv** [comment]
Sorry for reopening and closing, I tried to unselect the closing reason, but it seems impossible.
